"use client";
import {useEffect,useState} from "react";
import {hs2Catalog} from "../../lib/hs-catalog";

type Intel={country:string;hs:string;product:string;annual:Array<{period:string;value:number;status:string}>;current:{year:number;monthsReported:number;value:number;annualizedValue:number;status:string};outlook:{nextYear:number;value:number;direction:string;growthRate:number;confidence:number;method:string};supply:{period:number;worldImports:number;africanSuppliers:Array<{country:string;value:number;share:number;status:string}>;status:string};sources:Array<{name:string;type:string;url:string}>;warnings:string[]};
const products=["0702 — Tomatoes","0703 — Onions","1006 — Rice","1207 — Oilseeds","1509 — Vegetable oils","1801 — Cocoa beans","2523 — Cement","2710 — Refined petroleum","3004 — Medicines","7208 — Flat-rolled steel","8701 — Tractors","0102 — Live cattle",...hs2Catalog.map(([code,name])=>`${code} — ${name}`)];
const usd=(n:number)=>n?new Intl.NumberFormat("en",{style:"currency",currency:"USD",notation:"compact",maximumFractionDigits:1}).format(n):"No record";

export default function ImportIntelligence({country}:{country:string}){
 const [product,setProduct]=useState(products[1]),[data,setData]=useState<Intel|null>(null),[state,setState]=useState("Enter any HS2, HS4 or HS6 code, or choose a product.");
 useEffect(()=>{setData(null);setState(`Ready to examine ${country}.`)},[country]);
 async function run(){setState("Checking historical, current and African supplier records…");setData(null);const hs=(product.match(/^\d{2,6}/)?.[0]||product).replace(/\D/g,"").slice(0,6);if(hs.length<2){setState("Enter a valid 2, 4 or 6 digit HS code.");return}const response=await fetch(`/api/import-intelligence?country=${encodeURIComponent(country)}&hs=${hs}`);const result=await response.json() as Intel&{error?:string};if(response.ok){setData(result);setState("")}else setState(result.error||"No result was returned.")}
 return <section className="intel"><div className="intelhead"><div><p>PAST · PRESENT · POSSIBLE FUTURE</p><h2>What is {country} importing?</h2><span>Search any HS2, HS4 or HS6 product. Official records remain separate from projections and buyer claims.</span></div><div><label>Product / HS code<input list="hs-products" value={product} onChange={e=>setProduct(e.target.value)} placeholder="e.g. 0703 or onions"/><datalist id="hs-products">{products.map(x=><option value={x} key={x}/>)}</datalist></label><button onClick={run}>Build demand outlook</button></div></div>
  {data?<div className="intelbody"><div className="history"><small>REPORTED IMPORT HISTORY</small><h3>{data.product}</h3>{data.annual.map(x=>{const max=Math.max(...data.annual.map(a=>a.value),1);return <div className="bar" key={x.period}><i>{x.period}</i><span><b style={{width:`${x.value/max*100}%`}}/></span><strong>{usd(x.value)}</strong><em>{x.status}</em></div>})}</div><div className="now"><small>IMPORTING NOW</small><b>{usd(data.current.value)}</b><p>{data.current.monthsReported?`${data.current.monthsReported} month(s) reported for ${data.current.year}. Annualized pace: ${usd(data.current.annualizedValue)}.`:`No ${data.current.year} monthly record returned yet. Do not interpret this as zero demand.`}</p><i>{data.current.status}</i></div><div className="forecast"><small>POSSIBLE NEXT-YEAR DEMAND</small><b>{usd(data.outlook.value)}</b><h3>{data.outlook.direction} · {(data.outlook.growthRate*100).toFixed(1)}%</h3><p>{data.outlook.method}. This is a market signal, not verified buyer demand.</p><div><span style={{width:`${data.outlook.confidence}%`}}/><i>{data.outlook.confidence}% confidence</i></div></div><div className="suppliers"><small>RECORDED AFRICAN SUPPLIERS · {data.supply.period}</small>{data.supply.africanSuppliers.length?data.supply.africanSuppliers.map((x,i)=><article key={x.country}><i>{String(i+1).padStart(2,"0")}</i><span><b>{x.country}</b><small>{(x.share*100).toFixed(1)}% of recorded world imports</small></span><strong>{usd(x.value)}</strong></article>):<p>No African partner record was returned. This is a sourcing gap to investigate, not proof that supply is unavailable.</p>}</div><div className="provenance"><small>FREE INSTITUTIONAL SOURCES</small>{data.sources.map(x=><a href={x.url} target="_blank" rel="noreferrer" key={x.name}><b>{x.name}</b><span>{x.type} ↗</span></a>)}</div><footer>{data.warnings.map(x=><span key={x}>• {x}</span>)}</footer></div>:<div className="intelstate">{state}</div>}
 </section>
}
