"use client";
import { FormEvent, useEffect, useState } from "react";
type Deal = { id:number; reference:string; product:string };
type Dispute = { id:number; reference:string; dealId:number; category:string; status:string; disputedAmount:number; currency:string };
export default function DisputeCenter(){
  const [deals,setDeals]=useState<Deal[]>([]),[rows,setRows]=useState<Dispute[]>([]),[state,setState]=useState("Loading…");
  async function load(){const [a,b]=await Promise.all([fetch("/api/deals"),fetch("/api/disputes")]);if(a.status===401||b.status===401){location.href="/api/auth/signin?callbackUrl=/disputes";return}const da=await a.json(),db=await b.json();setDeals(da.deals||[]);setRows(db.disputes||[]);setState("")}
  useEffect(()=>{load()},[]);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setState("Opening case…");const form=e.currentTarget;const r=await fetch("/api/disputes",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(form)))});const d=await r.json();if(r.ok){form.reset();await load()}else setState(d.error||"Could not open case.")}
  return <main className="portal"><header><div className="brand"><i>TS</i><span><b>TradeSafe Africa</b><small>Resolution center</small></span></div><nav><a href="/dashboard">My deals</a><a href="/">Atlas</a></nav></header><section className="portalhead"><div><p>DOCUMENTED RESOLUTION</p><h1>Disputes & evidence</h1></div><aside><b>{rows.filter(x=>!["resolved","closed"].includes(x.status)).length}</b><span>open cases</span></aside></section><section className="roomgrid disputegrid"><article><div className="roomtitle"><small>OPEN A CASE</small><b>Deal owners only</b></div><form className="caseform" onSubmit={submit}><label>Deal<select name="dealId" required defaultValue=""><option value="" disabled>Select a deal</option>{deals.map(d=><option key={d.id} value={d.id}>{d.reference} — {d.product}</option>)}</select></label><label>Issue<select name="category" required><option value="quality">Quality or specification</option><option value="quantity">Quantity shortage</option><option value="delivery">Late or failed delivery</option><option value="payment">Payment disagreement</option><option value="documents">Document discrepancy</option><option value="fraud">Suspected fraud</option></select></label><label>Amount in dispute<input name="disputedAmount" type="number" min="0" step="0.01" /></label><label>Currency<select name="currency"><option>USD</option><option>GHS</option><option>NGN</option><option>XOF</option><option>KES</option><option>ZAR</option></select></label><label className="wide">What happened?<textarea name="description" minLength={20} required placeholder="Describe dates, commitments, delivery condition and evidence available." /></label><label className="wide">Requested resolution<textarea name="requestedResolution" placeholder="Refund, replacement, corrected documents, inspection…" /></label><button>Open documented case</button><small>{state}</small></form></article><article><div className="roomtitle"><small>YOUR CASES</small><b>Append-only history</b></div>{rows.length?rows.map(x=><div className="case" key={x.id}><div><b>{x.reference}</b><small>Deal #{x.dealId} · {x.category.replaceAll("_"," ")}</small></div><strong>{x.status.replaceAll("_"," ")}</strong><span>{x.disputedAmount?`${x.currency} ${x.disputedAmount.toLocaleString()}`:"Amount not stated"}</span></div>):<div className="portalempty"><h2>No cases</h2><p>Use this center after you have tried to resolve the issue with the counterparty.</p></div>}</article></section><section className="resolutionnote"><b>Important:</b> Opening a case records your report and starts an evidence review. It does not prove a claim, freeze funds, or guarantee recovery. Only a licensed payment or escrow partner can hold or release money.</section></main>;
}
