"use client";
import { useEffect,useMemo,useState } from "react";
import ImportIntelligence from "./components/ImportIntelligence";
import { africaCountryPaths } from "./africa-map-data";
type C={n:string;c:string;x:number;y:number;r:string;exp:number;imp:number};
const raw=`Algeria|DZ|51|9|north|5.8|4.2
Angola|AO|47|63|south|2.1|1.6
Benin|BJ|35|43|west|1.2|2
Botswana|BW|56|78|south|5.1|4.7
Burkina Faso|BF|31|38|west|1.1|1.8
Burundi|BI|68|56|east|.12|.42
Cabo Verde|CV|8|30|west|.08|.42
Cameroon|CM|45|45|central|1.7|2.2
Central African Republic|CF|52|47|central|.09|.28
Chad|TD|51|35|central|.65|1
Comoros|KM|84|67|east|.05|.24
Republic of Congo|CG|50|54|central|.75|.9
Côte d’Ivoire|CI|25|46|west|6.4|4.8
DR Congo|CD|55|58|central|3|3.4
Djibouti|DJ|78|39|east|.55|1.3
Egypt|EG|66|12|north|8.8|7.4
Equatorial Guinea|GQ|42|51|central|.55|.45
Eritrea|ER|72|31|east|.21|.37
Eswatini|SZ|63|82|south|2.2|2
Ethiopia|ET|68|39|east|1.5|3.8
Gabon|GA|44|54|central|1.1|1
Gambia|GM|15|37|west|.13|.48
Ghana|GH|29|45|west|4.8|3.2
Guinea|GN|19|42|west|1.4|1.2
Guinea-Bissau|GW|16|40|west|.12|.25
Kenya|KE|72|53|east|4.1|3.7
Lesotho|LS|58|88|south|.8|1.6
Liberia|LR|21|47|west|.25|.72
Libya|LY|55|18|north|3.6|2.5
Madagascar|MG|84|74|east|.72|1.1
Malawi|MW|64|67|south|.65|1.15
Mali|ML|27|34|west|1.3|2.1
Mauritania|MR|20|26|west|.75|.85
Mauritius|MU|94|73|east|1.25|1.45
Morocco|MA|36|5|north|9.7|6.8
Mozambique|MZ|72|72|south|2|2.7
Namibia|NA|44|76|south|3.1|3.5
Niger|NE|39|31|west|.65|1.4
Nigeria|NG|40|44|west|8.2|5.9
Rwanda|RW|69|54|east|.85|1.25
São Tomé & Príncipe|ST|39|54|central|.025|.09
Senegal|SN|14|34|west|2.2|3
Seychelles|SC|91|59|east|.16|.31
Sierra Leone|SL|18|45|west|.32|.62
Somalia|SO|82|45|east|.42|1.7
South Africa|ZA|55|92|south|30.4|13.8
South Sudan|SS|63|46|east|.42|.68
Sudan|SD|62|31|north|1.15|1.4
Tanzania|TZ|68|60|east|3.2|3
Togo|TG|33|43|west|1.05|1.4
Tunisia|TN|53|4|north|4.6|3.5
Uganda|UG|67|52|east|2.1|2.2
Zambia|ZM|58|67|south|3.5|3.1
Zimbabwe|ZW|59|74|south|2.3|2.8`;
const cs:C[]=raw.split("\n").map(s=>{const [n,c,x,y,r,exp,imp]=s.split("|");return {n,c,x:+x,y:+y,r,exp:+exp,imp:+imp}});
const profiles:Record<string,{sell:string[];need:string[];partners:string[];legal:string[];margin:[number,number]}>= {
 west:{sell:["processed foods","steel & cement","cocoa / cashew","textiles"],need:["vegetables & grains","fuel","machinery","medicines"],partners:["Ghana","Nigeria","Côte d’Ivoire","Senegal"],legal:["ECOWAS/ETLS origin status","exporter and importer registration","customs declaration and HS code","SPS or product certification"],margin:[6,18]},
 east:{sell:["tea & coffee","food products","cement","textiles"],need:["fuel","machinery","fertiliser","medicines"],partners:["Kenya","Tanzania","Uganda","Ethiopia"],legal:["EAC/COMESA origin documents","customs agent appointment","standards conformity","SPS or pharmacy permit"],margin:[5,16]},
 south:{sell:["minerals","machinery","food products","electricity"],need:["fuel","consumer goods","industrial inputs","medicines"],partners:["South Africa","Zambia","Botswana","Mozambique"],legal:["SADC origin certificate","import/export registration","customs value declaration","standards and labelling"],margin:[4,14]},
 north:{sell:["fertiliser","chemicals","textiles","processed food"],need:["livestock","minerals","machinery","food inputs"],partners:["Egypt","Morocco","Tunisia","Algeria"],legal:["AfCFTA or regional proof of origin","foreign-exchange compliance","customs and VAT registration","local-language labelling"],margin:[5,15]},
 central:{sell:["timber","minerals","livestock","petroleum"],need:["food","machinery","construction goods","medicines"],partners:["Cameroon","DR Congo","Congo","Gabon"],legal:["CEMAC/ECCAS origin evidence","import/export licence","customs declaration","sector-specific permits"],margin:[7,20]}
};
const money=(v:number)=>v<1?`$${Math.round(v*1000)}M`:`$${v.toFixed(1)}B`;
const lanes=[
 {product:"0703 — Onions",origin:"Burkina Faso",destination:"Ghana",buy:14800,sell:20500,freight:2100,border:850,loss:5,finance:420,unit:"20-tonne truck",signal:"Strong seasonal import pattern",docs:["commercial invoice","ECOWAS proof of origin","phytosanitary certificate","customs declaration"]},
 {product:"0102 — Live cattle",origin:"Burkina Faso",destination:"Ghana",buy:24500,sell:33000,freight:3100,border:1200,loss:2,finance:700,unit:"25 head",signal:"Established livestock corridor",docs:["veterinary health certificate","movement permit","ECOWAS origin evidence","customs declaration"]},
 {product:"2523 — Cement",origin:"Ghana",destination:"Burkina Faso",buy:19000,sell:24900,freight:2800,border:700,loss:1,finance:480,unit:"30-tonne truck",signal:"Recurring construction demand",docs:["commercial invoice","ETLS certificate for approved product","standards conformity","transit/customs declaration"]},
 {product:"7208 — Flat-rolled steel",origin:"Ghana",destination:"Burkina Faso",buy:28500,sell:36500,freight:3300,border:900,loss:.5,finance:760,unit:"25 tonnes",signal:"Material trade already recorded",docs:["commercial invoice","certificate of origin","standards documentation","customs declaration"]},
 {product:"0702 — Tomatoes",origin:"Burkina Faso",destination:"Ghana",buy:11200,sell:17600,freight:1950,border:650,loss:12,finance:350,unit:"18-tonne truck",signal:"High demand, high spoilage risk",docs:["phytosanitary certificate","commercial invoice","agricultural origin evidence","customs declaration"]},
 {product:"1801 — Cocoa beans",origin:"Ghana",destination:"Togo",buy:32000,sell:38500,freight:1600,border:950,loss:1,finance:800,unit:"10 tonnes",signal:"Regulated commodity—licence critical",docs:["licensed cocoa export approval","quality certificate","certificate of origin","customs declaration"]}
];
export default function Home(){
 const [code,setCode]=useState("GH"),[q,setQ]=useState(""),[flow,setFlow]=useState<"imp"|"exp">("imp");
 const [buy,setBuy]=useState(20000),[sell,setSell]=useState(26000),[freight,setFreight]=useState(2600),[border,setBorder]=useState(1400),[loss,setLoss]=useState(3),[finance,setFinance]=useState(500);
 const [product,setProduct]=useState("0702 — Tomatoes"),[origin,setOrigin]=useState("Burkina Faso"),[destination,setDestination]=useState("Ghana"),[volume,setVolume]=useState("20 tonnes"),[contact,setContact]=useState(""),[requestState,setRequestState]=useState(""),[officialFlow,setOfficialFlow]=useState("Not checked yet."),[role,setRole]=useState("wanted"),[classifieds,setClassifieds]=useState<Array<{id:number;role:string;origin:string;destination:string;product:string;volume:string;status:string;createdAt:string}>>([]);
 const [safety,setSafety]=useState({identity:false,business:false,order:false,stock:false,payment:false,truck:false,documents:false,inspection:false}),[protectState,setProtectState]=useState("");
 const c=cs.find(x=>x.c===code)!; const p=profiles[c.r]; const visible=useMemo(()=>cs.filter(x=>x.n.toLowerCase().includes(q.toLowerCase())),[q]);
 useEffect(()=>{fetch("/api/market-requests").then(r=>r.json()).then(d=>setClassifieds(d.requests||[])).catch(()=>{})},[]);
 const total=buy+freight+border+(buy*loss/100)+finance, profit=sell-total, margin=sell?profit/sell*100:0;
 const safeCount=Object.values(safety).filter(Boolean).length,safeScore=Math.round(safeCount/8*100);
 return <main><header><div className="brand"><i>AT</i><span><b>Africa Trade Atlas</b><small>Find the gap. Build the corridor.</small></span></div><div className="status">● Directional 2024 estimates · 54 countries · <a href="/built">What is built →</a> · <a href="/opportunities">Find an opportunity →</a> · <a href="/dashboard">My TradeSafe desk →</a></div></header>
 <section className="intro"><div><p>INTRA-AFRICAN OPPORTUNITY EXPLORER</p><h1>What does Africa need<br/>from <em>Africa?</em></h1></div><aside>Select a country to uncover regional trade, profit ranges, legal hurdles and a route from market gap to first transaction.</aside></section>
 <section className="buildstatus" aria-label="Product development status"><div className="buildflag"><i>PRIVATE ALPHA</i><b>Partly functional—not transaction complete.</b></div><div><p>IS THIS SITE FULLY FUNCTIONAL?</p><h2>No. Its research and deal-preparation tools work; live trade execution does not.</h2><span>You can explore 54 countries, check official trade records, calculate landed costs, post classifieds, create persistent deal rooms and open disputes. The site cannot yet produce a verified transaction-ready buyer, collect binding quotes, accept identity documents, book logistics or hold money.</span></div><div className="buildcols"><article><small>FUNCTIONAL NOW</small><b>Research and deal preparation</b><span>Interactive country map · official-data lookups · HS search · editable economics · classifieds intake · authenticated deal rooms · administrative evidence review · dispute records</span></article><article><small>NOT FUNCTIONAL YET</small><b>Verified transaction execution</b><span>automatic live matching · verified ready buyers and suppliers · binding quote collection · secure document uploads · freight booking · inspection booking · licensed escrow or payment custody</span></article></div><footer><b>Bottom line:</b> use the site to find and prepare a possible deal. Do not use it as proof that a buyer, supplier, price, permit, shipment or payment arrangement is verified. <a href="/built">See the complete product ledger →</a></footer></section>
 <section className="lanes"><div className="laneintro"><p>NEARBY TRADE LANE FINDER</p><h2>Start with a deal—not a continent.</h2><span>Ranked screening opportunities for a small trader based in Ghana. Costs are editable assumptions; counterparties are shown only after verification.</span></div><div className="lanetable"><div className="lanehdr"><span>PRODUCT & ROUTE</span><span>SHIPMENT</span><span>EST. PROFIT</span><span>MARGIN</span><span>STATUS</span><span/></div>{lanes.map((l,i)=>{const landed=l.buy+l.freight+l.border+l.buy*l.loss/100+l.finance;const gain=l.sell-landed;return <div className="lanerow" key={l.product+l.destination}><span><b>{l.product.split(" — ")[1]}</b><small>{l.origin} → {l.destination}</small></span><span>{l.unit}</span><span className={gain>0?"positive":"negative"}>${gain.toLocaleString()}</span><span>{(gain/l.sell*100).toFixed(1)}%</span><span><i>MARKET SIGNAL</i><small>0 verified live orders</small></span><button onClick={()=>{setProduct(l.product);setOrigin(l.origin);setDestination(l.destination);setVolume(l.unit);setBuy(l.buy);setSell(l.sell);setFreight(l.freight);setBorder(l.border);setLoss(l.loss);setFinance(l.finance);document.getElementById("deal-economics")?.scrollIntoView({behavior:"smooth"})}}>Open deal →</button></div>})}</div></section>
 <section className="tradesafe"><div className="tsintro"><p>TRADESAFE PROTECTION</p><h2>Do not move money until the evidence is green.</h2><span>Selected deal: <b>{product.split(" — ")[1]}</b>, {origin} → {destination}</span><div className={`score ${safeScore<50?"red":safeScore<88?"amber":"green"}`}><strong>{safeScore}</strong><i>/100</i><small>{safeScore===100?"READY FOR FINAL REVIEW":safeScore>=50?"CONDITIONS OUTSTANDING":"STOP — HIGH EXPOSURE"}</small></div></div><div className="checks">{([['identity','Government ID and liveness'],['business','Company and beneficial owner'],['order','Buyer order and authority'],['stock','Stock existence and quantity'],['payment','Protected payment arrangement'],['truck','Driver, vehicle and route'],['documents','Customs and product documents'],['inspection','Independent loading inspection']] as const).map(([k,label],i)=><label className={safety[k]?"done":""} key={k}><input type="checkbox" checked={safety[k]} onChange={e=>setSafety({...safety,[k]:e.target.checked})}/><b>0{i+1}</b><span>{label}<small>{safety[k]?"Evidence marked received":"Evidence required"}</small></span><i>{safety[k]?"✓":"—"}</i></label>)}</div><div className="protect"><div><small>PROTECTION REQUEST</small><b>We coordinate checks; regulated partners hold or transmit funds.</b><span>No guarantee of profit, delivery or dispute recovery is implied.</span></div><label>Private contact<input value={contact} onChange={e=>setContact(e.target.value)} placeholder="Email or WhatsApp"/></label><button onClick={async()=>{setProtectState("Submitting…");const r=await fetch("/api/market-requests",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({role:"protection_request",origin,destination,product,volume,contact})});setProtectState(r.ok?"Protection request received.":"Add your contact and try again.")}}>Start TradeSafe review</button><strong>{protectState}</strong></div></section>
 <section className="desk"><nav><label>⌕ <input value={q} onChange={e=>setQ(e.target.value)} placeholder="Find a country…"/></label><div className="toggle"><button className={flow==="imp"?"on":""} onClick={()=>setFlow("imp")}>Import demand</button><button className={flow==="exp"?"on":""} onClick={()=>setFlow("exp")}>Export supply</button></div><small>COUNTRIES <b>{visible.length}</b></small><div className="list">{visible.map(x=><button className={x.c===code?"pick":""} onClick={()=>setCode(x.c)} key={x.c}><i>{x.c}</i><span>{x.n}</span><b>{money(x[flow])}</b></button>)}</div></nav>
 <div className="map"><div className="scale">NATURAL EARTH · COUNTRY BOUNDARIES</div><svg className="africa" viewBox="0 0 100 100" role="img" aria-label="Interactive political map of Africa">{africaCountryPaths.map(country=><path key={country.code} d={country.path} className={`country ${country.code===code?"selected":""}`} onClick={()=>setCode(country.code)}><title>{country.name}</title></path>)}</svg>{cs.filter(x=>!africaCountryPaths.some(country=>country.code===x.c)).map(x=><button aria-label={x.n} title={x.n} onClick={()=>setCode(x.c)} className={`pin island ${x.c===code?"sel":""}`} style={{left:x.x+"%",top:x.y+"%"}} key={x.c}><span>{x.c}</span></button>)}<p>Select a country shape or island marker to open its deal brief</p></div>
 <article className="brief"><div className="ct"><i>{c.c}</i><span><small>COUNTRY BRIEF</small><h2>{c.n}</h2></span></div><div className="nums"><span><small>REGIONAL EXPORTS</small><b>{money(c.exp)}</b></span><span><small>REGIONAL IMPORTS</small><b>{money(c.imp)}</b></span></div><h3>Likely supply strengths</h3><div className="chips green">{p.sell.map(x=><i key={x}>{x}</i>)}</div><h3>Needs worth validating</h3><div className="chips gold">{p.need.map(x=><i key={x}>{x}</i>)}</div><h3>Regional corridors</h3>{p.partners.filter(x=>x!==c.n).slice(0,3).map((x,i)=><div className="route" key={x}><b>0{i+1}</b>{c.n} ↔ {x}<i>→</i></div>)}</article></section>
 <ImportIntelligence country={c.n}/>
 <section className="productdesk"><div className="pdhead"><p>PRODUCT & HS-CODE DESK</p><h2>Move from a country idea to a shipment question.</h2><span>Choose a product and corridor. Official evidence is fetched separately from private-market verification.</span></div><div className="productgrid"><label>Listing type<select value={role} onChange={e=>setRole(e.target.value)}><option value="wanted">Wanted</option><option value="for_sale">For sale</option><option value="freight_available">Freight available</option></select></label><label>Product / HS code<select value={product} onChange={e=>setProduct(e.target.value)}>{["0702 — Tomatoes","0703 — Onions","1006 — Rice","1207 — Oilseeds","1509 — Vegetable oils","1801 — Cocoa beans","2523 — Cement","2710 — Refined petroleum","3004 — Medicines","7208 — Flat-rolled steel","8701 — Tractors","0102 — Live cattle"].map(x=><option key={x}>{x}</option>)}</select></label><label>Origin<select value={origin} onChange={e=>setOrigin(e.target.value)}>{cs.map(x=><option key={x.c}>{x.n}</option>)}</select></label><label>Destination<select value={destination} onChange={e=>setDestination(e.target.value)}>{cs.map(x=><option key={x.c}>{x.n}</option>)}</select></label><label>Volume<input value={volume} onChange={e=>setVolume(e.target.value)}/></label><label>Business email / phone<input value={contact} onChange={e=>setContact(e.target.value)} placeholder="Private; required"/></label><button onClick={async()=>{setRequestState("Submitting…");const res=await fetch("/api/market-requests",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({role,origin,destination,product,volume,contact})});if(res.ok){setRequestState("Listed pending verification.");const d=await fetch("/api/market-requests").then(x=>x.json());setClassifieds(d.requests||[])}else setRequestState("Please complete every field.")}}>Post classified & request matches</button></div><div className="sourcechecks"><article><i>LIVE FREE SOURCE</i><b>UN Comtrade trade flow</b><span>{officialFlow}</span><button onClick={async()=>{setOfficialFlow("Checking official records…");const r=await fetch(`/api/official-flow?origin=${encodeURIComponent(origin)}&destination=${encodeURIComponent(destination)}&hs=${product.split(" ")[0]}`);const d=await r.json();setOfficialFlow(r.ok?`${d.period}: $${Number(d.value).toLocaleString()} recorded exports; ${d.records} record(s).`:d.error)}}>Check official flow</button></article><article><i>OFFICIAL</i><b>Tariff & non-tariff measures</b><span>Check origin preference and destination measures in ITC MacMap.</span><a href="https://www.macmap.org/" target="_blank" rel="noreferrer">Check tariff ↗</a></article><article><i>VERIFICATION</i><b>Buyer, supplier & price</b><span>Contact stays private. Matching happens after identity and authority checks.</span><strong>{requestState||"No listing submitted yet."}</strong></article></div></section>
 <section className="classifieds"><div className="classhead"><p>TRADE CLASSIFIEDS</p><h2>Demand, supply and trucks looking for a match.</h2><span>Public details exclude private contact information. “Pending” means the claim has not yet been verified.</span></div><div className="classgrid">{classifieds.length?classifieds.map(x=><article key={x.id}><div><i>{x.role.replaceAll("_"," ")}</i><b className={x.status==="verified"?"verified":"pending"}>{x.status.replaceAll("_"," ")}</b></div><h3>{x.product}</h3><p>{x.origin} → {x.destination}</p><strong>{x.volume}</strong><button>Request verified introduction</button></article>):<div className="empty"><b>No classifieds yet.</b><span>Be the first to post a genuine demand, supply or freight listing. It will appear here as pending verification.</span></div>}</div></section>
 <section className="deal" id="deal-economics"><div className="dealhead"><p>DEAL ECONOMICS</p><h2>{product.split(" — ")[1]}: {origin} → {destination}</h2><span>Change every assumption. Profit is after the listed landed costs, before company income tax.</span></div><div className="calc"><label>Supplier cost ($)<input type="number" value={buy} onChange={e=>setBuy(+e.target.value)}/></label><label>Buyer revenue ($)<input type="number" value={sell} onChange={e=>setSell(+e.target.value)}/></label><label>Freight & handling ($)<input type="number" value={freight} onChange={e=>setFreight(+e.target.value)}/></label><label>Duty, VAT & border ($)<input type="number" value={border} onChange={e=>setBorder(+e.target.value)}/></label><label>Loss / spoilage (%)<input type="number" value={loss} onChange={e=>setLoss(+e.target.value)}/></label><label>Finance & FX ($)<input type="number" value={finance} onChange={e=>setFinance(+e.target.value)}/></label></div><div className={`result ${profit<0?"bad":""}`}><span><small>LANDED COST</small><b>${total.toLocaleString()}</b></span><span><small>EST. NET PROFIT</small><b>${profit.toLocaleString()}</b></span><span><small>NET MARGIN</small><b>{margin.toFixed(1)}%</b></span><p>Break-even selling price: <b>${total.toLocaleString()}</b>. Require a written buyer order and fresh quotes before treating this estimate as actionable.</p></div></section>
 <section className="execution"><div><p>SHIPMENT-READY CHECK</p><h2>What this selected deal needs</h2></div><div className="execgrid"><article><small>COUNTERPARTIES</small><b>0 verified live orders</b><p>Submit the request above. A buyer or supplier appears here only after identity, authority, stock/demand and contact evidence are checked.</p></article><article><small>REQUIRED DOCUMENTS</small>{(lanes.find(l=>l.product===product&&l.origin===origin&&l.destination===destination)?.docs||["commercial invoice","packing list","proof of origin","customs declaration","product-specific permit"]).map(x=><span key={x}>✓ {x}</span>)}</article><article><small>GO / NO-GO</small><b className={profit>0?"go":"nogo"}>{profit>0?"PROVISIONAL GO":"NO-GO"}</b><p>{profit>0?"Economics pass the first screen. Buyer, price, permits and freight still require verification.":"The current assumptions destroy value. Renegotiate before proceeding."}</p></article></div></section>
 <section className="passport"><div className="passhead"><span>TP</span><div><p>DIGITAL TRADE PASSPORT</p><h2>{product.split(" — ")[1]} · {origin} to {destination}</h2></div><i>DRAFT</i></div><div className="passgrid"><article><small>COMMERCIAL</small><b>Shipment</b><span>{volume}</span><b>Supplier cost</b><span>${buy.toLocaleString()}</span><b>Buyer value</b><span>${sell.toLocaleString()}</span></article><article><small>PARTIES</small><b>Buyer</b><span>{safety.order?"Order evidence received":"Not verified"}</span><b>Supplier</b><span>{safety.stock?"Stock evidence received":"Not verified"}</span><b>Business KYC</b><span>{safety.business?"Marked received":"Not verified"}</span></article><article><small>LOGISTICS</small><b>Vehicle & driver</b><span>{safety.truck?"Marked verified":"Not assigned"}</span><b>Loading inspection</b><span>{safety.inspection?"Evidence received":"Required"}</span><b>Documents</b><span>{safety.documents?"Marked complete":"Incomplete"}</span></article><article><small>PAYMENT & RELEASE</small><b>Payment protection</b><span>{safety.payment?"Arrangement marked received":"Not arranged"}</span><b>Release condition</b><span>Delivery evidence + buyer acceptance</span><b>Safety score</b><span>{safeScore}/100</span></article></div><div className="milestones">{[["1","Contract","10%"],["2","Verified loading","40%"],["3","Border clearance","40%"],["4","Delivery acceptance","10%"]].map(x=><span key={x[0]}><i>{x[0]}</i><b>{x[1]}</b><small>{x[2]} suggested milestone</small></span>)}</div><p className="passnote">Illustrative milestone structure only. A licensed bank or payment provider must determine and execute the lawful payment arrangement.</p></section>
 <section className="insouts"><div><p>LEGAL & CUSTOMS</p><h2>What must be true before goods move</h2></div><div className="cards">{p.legal.map((x,i)=><article key={x}><b>0{i+1}</b><h3>{x}</h3><p>Confirm with destination customs and a licensed broker using the product HS code.</p></article>)}</div><div className="matrix"><article><h3>Documents usually required</h3><ul><li>Commercial invoice and packing list</li><li>Transport document / waybill</li><li>Customs declaration and correct HS code</li><li>Proof or certificate of origin</li><li>Insurance certificate</li><li>Health, phytosanitary or standards permit</li></ul></article><article><h3>Costs people miss</h3><ul><li>Loading, unloading and market levies</li><li>Broker and terminal charges</li><li>Demurrage, delay and checkpoints</li><li>Spoilage, shrinkage and rejected grades</li><li>FX spread and transfer fees</li><li>VAT cash-flow</li></ul></article><article><h3>Deal-killers</h3><ul><li>No verified buyer purchase order</li><li>Bank account mismatch</li><li>Cash advances to unverified agents</li><li>Preference assumed without origin proof</li><li>No quality specification or inspection</li><li>No allocation of border and loss risk</li></ul></article></div></section>
 <section className="play">{[["01","VERIFY","Interview five buyers","Record volume, grade, price, seasonality and current supplier."],["02","PRICE","Build landed cost","Quote every charge and add delay and FX contingencies."],["03","PROTECT","Contract the pilot","Use inspection, deposits, milestones and clear Incoterms."],["04","SCALE","Repeat before inventory","Broker first. Finance stock after successful cycles."]].map(a=><div key={a[0]}><b>{a[0]}</b><p>{a[1]}</p><h3>{a[2]}</h3><span>{a[3]}</span></div>)}</section>
 <section className="sources"><div><p>VERIFY BEFORE YOU TRADE</p><h2>Use the map to find the question—not to skip due diligence.</h2></div><div><a href="https://comtradeplus.un.org/" target="_blank" rel="noreferrer">UN Comtrade <span>Trade flows ↗</span></a><a href="https://www.macmap.org/" target="_blank" rel="noreferrer">ITC Market Access Map <span>Tariffs & measures ↗</span></a><a href="https://www.africancfta.org/" target="_blank" rel="noreferrer">AfCFTA Secretariat <span>Rules & protocols ↗</span></a><a href="https://etls.ecowas.int/" target="_blank" rel="noreferrer">ECOWAS ETLS <span>West African origin ↗</span></a></div></section>
 <footer><b>Africa Trade Atlas</b><span>Screening estimates, not legal, tax or investment advice. Verify the HS code, live tariff, origin eligibility, product permit and landed cost before every transaction.</span></footer></main>
}
