import { env } from "cloudflare:workers";
import { and, eq } from "drizzle-orm";
import { getChatGPTUser } from "../../../../chatgpt-auth";
import { getDb } from "../../../../../db";
import { dealDocuments, dealEvents, deals, documentAuditEvents, documentFiles } from "../../../../../db/schema";

const allowed=new Set(["application/pdf","image/jpeg","image/png"]),max=10*1024*1024;
function validMagic(bytes:Uint8Array,type:string){if(type==="application/pdf")return bytes[0]===0x25&&bytes[1]===0x50&&bytes[2]===0x44&&bytes[3]===0x46;if(type==="image/png")return bytes[0]===0x89&&bytes[1]===0x50&&bytes[2]===0x4e&&bytes[3]===0x47;if(type==="image/jpeg")return bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff;return false}
export async function POST(req:Request,{params}:{params:Promise<{id:string}>}){const user=await getChatGPTUser();if(!user)return Response.json({error:"Sign in required."},{status:401});const dealId=Number((await params).id);const form=await req.formData();const file=form.get("file"),documentId=Number(form.get("documentId"));if(!(file instanceof File)||!documentId)return Response.json({error:"Choose a required document and file."},{status:400});if(!allowed.has(file.type)||file.size>max)return Response.json({error:"Upload PDF, JPEG or PNG files up to 10 MB."},{status:400});const bytes=new Uint8Array(await file.arrayBuffer());if(!validMagic(bytes,file.type))return Response.json({error:"The file contents do not match its stated type."},{status:400});const db=getDb();const [[deal],[doc]]=await Promise.all([db.select().from(deals).where(and(eq(deals.id,dealId),eq(deals.ownerEmail,user.email))).limit(1),db.select().from(dealDocuments).where(and(eq(dealDocuments.id,documentId),eq(dealDocuments.dealId,dealId))).limit(1)]);if(!deal||!doc)return Response.json({error:"Deal document not found."},{status:404});const digest=await crypto.subtle.digest("SHA-256",bytes),sha256=Array.from(new Uint8Array(digest)).map(x=>x.toString(16).padStart(2,"0")).join("");const key=`deals/${dealId}/${documentId}/${crypto.randomUUID()}`;await env.BUCKET.put(key,bytes,{httpMetadata:{contentType:file.type},customMetadata:{owner:user.email,sha256}});try{const [saved]=await db.insert(documentFiles).values({dealDocumentId:documentId,dealId,uploaderEmail:user.email,storageKey:key,originalName:file.name.replace(/[^a-zA-Z0-9._ -]/g,"_"),contentType:file.type,sizeBytes:file.size,sha256}).returning();await db.update(dealDocuments).set({status:"submitted",storageKey:key,fileName:file.name,reportedBy:user.email}).where(eq(dealDocuments.id,documentId));await db.insert(documentAuditEvents).values({documentFileId:saved.id,dealId,actorEmail:user.email,action:"uploaded",details:`${file.type}; ${file.size} bytes; sha256 ${sha256}`});await db.insert(dealEvents).values({dealId,actorEmail:user.email,eventType:"document_uploaded",summary:`${doc.documentType.replaceAll("_"," ")} submitted for review`});return Response.json({file:{id:saved.id,name:saved.originalName,status:"submitted"}},{status:201});}catch(error){await env.BUCKET.delete(key);throw error}}
