"use client";
import {useMemo,useState} from "react";

const candidates=[
 {product:"Onions",hs:"0703",origin:"Burkina Faso",destination:"Ghana",shipment:"20-tonne truck",buy:14800,sell:20500,freight:2100,border:850,loss:5,finance:420,inspection:180,insurance:220,contingency:400,demand:82,supply:78,risk:48,buyer:"0 verified buyers"},
 {product:"Live cattle",hs:"0102",origin:"Burkina Faso",destination:"Ghana",shipment:"25 head",buy:24500,sell:33000,freight:3100,border:1200,loss:2,finance:700,inspection:250,insurance:300,contingency:600,demand:79,supply:74,risk:57,buyer:"0 verified buyers"},
 {product:"Cement",hs:"2523",origin:"Ghana",destination:"Burkina Faso",shipment:"30-tonne truck",buy:19000,sell:24900,freight:2800,border:700,loss:1,finance:480,inspection:180,insurance:240,contingency:350,demand:75,supply:83,risk:42,buyer:"0 verified buyers"},
 {product:"Flat-rolled steel",hs:"7208",origin:"Ghana",destination:"Burkina Faso",shipment:"25 tonnes",buy:28500,sell:36500,freight:3300,border:900,loss:.5,finance:760,inspection:220,insurance:350,contingency:500,demand:80,supply:85,risk:39,buyer:"0 verified buyers"},
 {product:"Tomatoes",hs:"0702",origin:"Burkina Faso",destination:"Ghana",shipment:"18-tonne truck",buy:11200,sell:17600,freight:1950,border:650,loss:12,finance:350,inspection:180,insurance:200,contingency:500,demand:86,supply:72,risk:68,buyer:"0 verified buyers"},
 {product:"Cocoa beans",hs:"1801",origin:"Ghana",destination:"Togo",shipment:"10 tonnes",buy:32000,sell:38500,freight:1600,border:950,loss:1,finance:800,inspection:250,insurance:350,contingency:450,demand:73,supply:88,risk:61,buyer:"0 verified buyers"},
];
const calc=(x:typeof candidates[number])=>{const spoil=x.buy*x.loss/100;const landed=x.buy+x.freight+x.border+spoil+x.finance+x.inspection+x.insurance+x.contingency;const profit=x.sell-landed;const score=Math.round(x.demand*.34+x.supply*.24+Math.max(0,100-x.risk)*.22+Math.max(0,Math.min(100,profit/x.sell*500))*.2);return {...x,spoil,landed,profit,margin:profit/x.sell*100,score}};

export default function Opportunities(){
 const [capital,setCapital]=useState(40000),[country,setCountry]=useState("All"),[risk,setRisk]=useState(70);
 const ranked=useMemo(()=>candidates.map(calc).filter(x=>x.landed<=capital&&x.risk<=risk&&(country==="All"||x.origin===country||x.destination===country)).sort((a,b)=>b.score-a.score),[capital,country,risk]);
 return <main className="finder"><header><div className="brand"><i>TS</i><span><b>TradeSafe Africa</b><small>Opportunity Finder</small></span></div><nav><a href="/">Atlas</a><a href="/dashboard">My deals</a><a href="/admin">Verification desk</a></nav></header>
  <section className="finderhead"><div><p>PRODUCT → CORRIDOR → COST → BUYER</p><h1>What should I move?</h1><span>Ranked screening opportunities. Live quotations and a verified buyer are required before money moves.</span></div><form><label>Available capital ($)<input type="number" value={capital} onChange={e=>setCapital(+e.target.value)}/></label><label>Country<select value={country} onChange={e=>setCountry(e.target.value)}><option>All</option><option>Ghana</option><option>Burkina Faso</option><option>Togo</option></select></label><label>Maximum risk<input type="range" min="20" max="90" value={risk} onChange={e=>setRisk(+e.target.value)}/><i>{risk}/100</i></label></form></section>
  <section className="ranked"><div className="rankhead"><span>RANK / OPPORTUNITY</span><span>COMPLETE LANDED COST</span><span>PROFIT</span><span>BUYER EVIDENCE</span><span>DECISION</span></div>{ranked.length?ranked.map((x,i)=><article key={x.hs+x.destination}><div><i>#{i+1}</i><span><b>{x.product}</b><small>HS {x.hs} · {x.origin} → {x.destination} · {x.shipment}</small></span></div><div><b>${x.landed.toLocaleString()}</b><small>Goods ${x.buy.toLocaleString()} · Freight ${x.freight.toLocaleString()} · Border ${x.border.toLocaleString()} · Loss ${x.spoil.toLocaleString()} · Finance/FX ${x.finance.toLocaleString()} · Inspection ${x.inspection.toLocaleString()} · Insurance ${x.insurance.toLocaleString()} · Contingency ${x.contingency.toLocaleString()}</small></div><div><b className={x.profit>0?"positive":"negative"}>${x.profit.toLocaleString()}</b><small>{x.margin.toFixed(1)}% estimated margin</small></div><div><b>Market signal only</b><small>{x.buyer}. Purchase order not verified.</small></div><div><strong>{x.score}</strong><small>/100 opportunity score</small><a href={`/deal/new?product=${encodeURIComponent(x.product)}&hs=${x.hs}&origin=${encodeURIComponent(x.origin)}&destination=${encodeURIComponent(x.destination)}`}>Open investigation →</a></div></article>):<div className="findempty"><b>No candidate fits these limits.</b><span>Increase available capital, country coverage or acceptable risk.</span></div>}</section>
  <footer className="findnote"><b>Complete cost means all currently modeled cost categories—not a live quotation.</b> Supplier price, freight, tariff, VAT, permits, inspection, insurance, FX and buyer price must be refreshed for the specific transaction.</footer>
 </main>
}
